---
- name: Ensure installed nginx
  apt:
    pkg: nginx
    state: present
    update_cache: yes
  tags:
    - nginx

- name: Start nginx
  service:
    name: nginx
    state: started
  tags:
    - nginx
