---
- hosts: dbservers
  gather_facts: False
  roles:
    - common
    - postgresql

- hosts: appservers
  gather_facts: True
  serial: 1
  roles:
    - common
    - java
    - users
    - app

- hosts: proxies
  gather_facts: False
  roles:
    - common

