---

- hosts: dbservers
  roles:
    - etc_hosts
    - common
    - postgresql
    - db

- hosts: appservers
  serial: 1
  roles:
    - etc_hosts
    - common
    - users
    - app

- hosts: dbservers
  roles:
    - post_db

- hosts: proxies
  vars:
    - app_port: "1234"
  roles:
    - etc_hosts
    - common
    - nginx

