---
- name: Update apt keys
  command: apt-key update
  tags:
    - apt

- name: Update apt cache
  apt: update_cache=yes
  tags:
    - apt

- name: Ensure installed vim
  apt:
    pkg=vim
    state=present
    update_cache=no
  tags:
    - vim

- name: Set filetype indent off
  lineinfile:
    dest=/etc/vim/vimrc
    line='filetype indent off'
    state=present
  tags:
    - vim
