---
- name: Run "update_cache=yes" if the last one is more than 24 hours ago
  apt:
    update_cache=yes
    cache_valid_time=86400
  tags:
    - always

- name: Ensure installed vim
  apt:
    pkg=vim
    state=present
    update_cache=no
  tags:
    - vim

- name: Set filetype indent off
  lineinfile:
    dest=/etc/vim/vimrc
    line='filetype indent off'
    state=present
  tags:
    - vim
